#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamarinComponentsTests.Droid.Resource", IsApplication=true)]

namespace XamarinComponentsTests.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int axisTitle = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int labelColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int labelSize = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int action_settings = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int axisLayout = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int background = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int chartAreaLayout = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int chartTitle = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int frame = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int gaugeHeader = 2131230733;
			
			// aapt resource value: 0x7f080003
			public const int gridLineLayout = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int iconView = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int label = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int labelLayout = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int layout = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int legendHeader = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int legendItemsLayout = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int legendScrollView = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int legendViewGroup = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int rootLayout = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int seriesLayout = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int circulargauge_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int treemap_layout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int sf__circular_gauge = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int sf_tree_map = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hello_world = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ChartAxis = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ChartAxis_axisTitle = 2;
			
			// aapt resource value: 0
			public const int ChartAxis_labelColor = 0;
			
			// aapt resource value: 1
			public const int ChartAxis_labelSize = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
