#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Images.Droid.Resource", IsApplication=true)]

namespace Images.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_xamarin_studio = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ide_xamarin_studio = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int image = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mono_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int xamarin_authorized_partner_2x = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int xamarin_copy = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int xamarin_hexagon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int xamarin_hexagon_gif = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int xamarin_hexagon_png = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int xamarin_jpg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int xamarin_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Xamarin_logo_and_wordmark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int xamarin_logo_copy = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Xamarin_logo_hexagon_blue_200x200 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int xamarin_premier_partner_2x = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int xamarin_studio = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int xamarin_tiff = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
